### ISSUE TITLE
Sorting algorithms

### ISSUE THREAD

**Issue by tasha06** [tasha06/Sorting-Algorithms#1]

**Comment by NidhiNivedita6** [comment]
Please assign me this @tasha06 . I will add Count Sort in C.

**Comment by ghost** [comment]
@tasha06 Can you please assign this to me as well. 
I would like to add Sorting Algorithms using Javascript.

**Comment by Mayankjha997** [comment]
Hello @tasha06 ;
I want to add merge sort in python, please assign this to me.

**Comment by tasha06** [comment]
Go ahead @Mayankjha997

**Comment by SakshiJoshi26** [comment]
Hello! Please assign me this issue, I will add sorting program in C.

**Comment by tasha06** [comment]
You may submit your PR @SakshiJoshi26
